### ISSUE TITLE
bin and blob literals support is missing

### ISSUE THREAD

**Issue by tsuyoshicho** [vim-jp/vim-vimlparser#101]
binary literals (0b0)
Supported at ?

blob literals (0z0)
Supported at [8\.1\.0735](https://github.com/vim/vim/commit/6e5ea8d2a995b32bbc5972edc4f827b959f2702f)

**Comment by mattn** [comment]
AFAICS, both of them are included.

https://github.com/vim-jp/vim-vimlparser/blob/master/test/test_number.vim

https://github.com/vim-jp/vim-vimlparser/blob/master/test/test_blob.vim

**Comment by tsuyoshicho** [comment]
oops...

**Comment by tsuyoshicho** [comment]
I need to close it, I'm sorry

**Comment by mattn** [comment]
:ok_man:
