### ISSUE TITLE
Move s:viml_builtin_functions to shared file?

### ISSUE THREAD

**Issue by blueyed** [vim-jp/vim-vimlparser#118]
Currently `s:viml_builtin_functions` is defined twice in both `py/pycompiler.vim` (https://github.com/vim-jp/vim-vimlparser/blob/edd6a79ebf52930452aeaec13e5a6f9423896379/py/pycompiler.vim#L825) and `js/jscompiler.vim`.

I think this should be shared, probably in `s:VimLParser.builtin_functions`.

It is likely also out of date.  It would be good if this could be used through some Vim function directly.

**Comment by blueyed** [comment]
I have created https://github.com/vim/vim/issues/4700 to ask about support in Vim for this.

**Comment by tyru** [comment]
> `s:VimLParser.builtin_functions`

Yes, currently vimlparser doesn't have such thing.
I want to implement it for #105.

Currently `scripts/update_builtin_commands.sh` checks vim source (`src/ex_cmds.h`).
I want to provide similar script for vim functions (parse `src/evalfunc.c`).

**Comment by blueyed** [comment]
Ok.  As per https://github.com/vim/vim/issues/4700 Vim is unlikely to provide this information itself.

However, `nvim_get_commands` exists already (although only for non-builtin).  Might be useful in general, but only for "dynamic" linting/parsing (i.e. not for vint, vimlparser.py etc, which need the list already).

**Comment by tyru** [comment]
Thanks for asking to vim/vim.
I didn't know `nvim_get_commands()` (because I'm not neovim user).
currently neovim ex commands is updated manually. it should help auto-update 👍 

Does neovim provide function list version of `nvim_get_commands()` ?

**Comment by tyru** [comment]
Created #123

**Comment by tyru** [comment]
I don't read nvim source code, because it MAY results in license violation when I write vim patch.
(@mattn has the same policy)

**Comment by blueyed** [comment]
> I don't read nvim source code, because it MAY results in license violation when I write vim patch.
> (@mattn has the same policy)

Interesting - can you elaborate?

**Comment by blueyed** [comment]
`nvim_get_commands` seems to just provide the internal information: https://github.com/neovim/neovim/blob/a46fe2e615bc5f4431cad04b67ac5ba0b67ed86c/src/nvim/api/buffer.c#L653-L684

**Comment by tyru** [comment]
> Interesting - can you elaborate?

[Neovim's license](https://github.com/neovim/neovim/blob/master/LICENSE) is Apache license.
But [Vim's license](https://github.com/vim/vim#copying) is Vim license.
I don't *clearly* say they are compatible.

**Comment by tyru** [comment]
> `nvim_get_commands` seems to just provide the internal information: https://github.com/neovim/neovim/blob/a46fe2e615bc5f4431cad04b67ac5ba0b67ed86c/src/nvim/api/buffer.c#L653-L684

sorry, I can't read it because of above reason 😓 
I'm just afraid of that.
