### ISSUE TITLE
E492: Not an editor command: redrawtabline

### ISSUE THREAD

**Issue by tyru** [vim-jp/vim-vimlparser#151]

**Comment by blueyed** [comment]
But it's there: https://github.com/vim-jp/vim-vimlparser/blob/9cc29eec7e83d749eee72e4b844c1199939303dd/autoload/vimlparser.vim#L2640 ?

**Comment by tyru** [comment]
oh, maybe I'm using old vint.
this is remind issue for me ... ;)

**Comment by blueyed** [comment]
Ah..!
Merged https://github.com/Kuniwak/vint/pull/318 - works there.

**Comment by tyru** [comment]
Great! Thanks :tada:
