### ISSUE TITLE
Handle default arguments with functions

### ISSUE THREAD

**Issue by blueyed** [vim-jp/vim-vimlparser#154]
This is not parsed currently:

```vim
function! TestFunction(test = 1)
    echo a:test
endfunction
```

Via https://github.com/Kuniwak/vint/issues/337.

**Comment by tyru** [comment]
I didn't know default arguments in Vim script.
what did patch version include it?

**Comment by jmdevin** [comment]
It looks like it was [8.1.1310](https://github.com/vim/vim/commit/42ae78cfff171fbd7412306083fe200245d7a7a6) back in May, so not that long ago. I had no idea either. That's actually how I discovered this issue; I read about it in the help and the very first time I tried to use it I received the error.

**Comment by tyru** [comment]
@jmdevin Thanks
