### ISSUE TITLE
Helping out with maintaining

### ISSUE THREAD

**Issue by blueyed** [vim-jp/vim-vimlparser#35]
There are a lot of pending and trivial pull requests with fixes.

@ynkdir 
Do you need help with maintaining?
(We could also move it to https://github.com/vimjas)

**Comment by ynkdir** [comment]
It would be helpful if you take maintainership.

**Comment by blueyed** [comment]
I am willing to help, please add me to the project.

**Comment by mattn** [comment]
@ynkdir You can transfer this repository into vim-jp. This is not offer nor proposal, just suggestion. Feel free to think.

**Comment by blueyed** [comment]
Also https://github.com/vimjas maybe.

**Comment by ynkdir** [comment]
Thank you @blueyed and @mattn.  I'll transfer this repository into vim-jp.

**Comment by blueyed** [comment]
@ynkdir 
Thank you!
