### ISSUE TITLE
Should clarify license notation more clearly

### ISSUE THREAD

**Issue by mattn** [vim-jp/vim-vimlparser#84]
LICENSE file says:

```
To the extent possible under law, Yukihiro Nakadaira has waived all copyright and 
related or neighboring rights to VimL parser.
```

This says attribution to Yuhikiro Nakadaira and Public Domain but not says problems caused by copy of source code. I suggest to write "Your Own Risk" into the doc..

**Comment by tyru** [comment]
As Bram noted here, if the code is newly written by hand (by not copy), we can use any license.

https://groups.google.com/d/topic/vim_dev/STvt-KMhV8s

> Generally, if you copy code, the copyright remains.  Thus the Vim 
license applies to that code. 
>
> If you rewrite the code in another language, thus it's newly written and 
not copied, you can use whatever license you like.  It doesn't matter 
that it is doing the same thing, functionality is not copyrighted. 
> If the changes are mechanical, you could run a tool to do the 
translation, then the copyright remains. 
>
> I cannot make exceptions, since code has been donated to Vim by many 
authors, I might not have written the code you are copying.

**Comment by rhysd** [comment]
> This says attribution to Yuhikiro Nakadaira and Public Domain but not says problems caused by copy of source code. I suggest to write "Your Own Risk" into the doc..

I totally agree. I think we should show sources are made public as Public Domain and there is no guarantee for them in `LICENSE`.

**Comment by rhysd** [comment]
I created a PR #84 as a draft. Could you please review it?
